# ./main.yml
---
mariadb_databases: []
mariadb_users: []
mariadb_root_password: ''
mariadb_auth_unix_plugin: true

  #mariadb_mirror: yum.mariadb.org
mariadb_version: '10.6'

mariadb_configure_swappiness: false
mariadb_swappiness: "0"

# 27 is default in /usr/share/doc/setup-*/uidgid
mariadb_system_user:
  name: 'mysql'
  uid: 27
  gid: 27
  shell: '/sbin/nologin'
  home: '/var/lib/mysql'
  comment: 'MySQL Server'

mariadb_logrotate:
  configure: true
  rotate: 3

# Network configuration (network.cnf)

mariadb_service: mariadb
mariadb_bind_address: '0.0.0.0'

# Server configuration
mariadb_server_cnf: {}

# Custom configuration
mariadb_custom_cnf: {}
